### ISSUE TITLE
Attractive software, but there's a mistake in the instructions and the program does not appear to work

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [Nefelim4ag/Ananicy#10]
Your instructions for Debian/Ubuntu are:

```
$ git clone https://github.com/Nefelim4ag/Ananicy.git
$ ./Ananicy/package.sh debian
$ dpkg -i ./Ananicy/ananicy-*.deb
```
But, on my (Mint) system, the last line threw an error. For it needs to be run as _root_.
(Also, it takes a while to realise that the initial instructions - the ones preceeding your mention of Arch - are not to be followed on Debian or Ubuntu.)

Worse: having followed the instructions (and run the last line as root) and rebooted, nothing is being re-niced; I tested with Skype and Smplayer.

**Comment by Nefelim4ag** [comment]
@ACinnamonUserInUK, https://github.com/Nefelim4ag/Ananicy/commit/e68db11d1a909a5e3b2a20c594160c1cbc26f98d
