### ISSUE TITLE
Rules files integrated into single conf

### ISSUE THREAD

**Issue by ryanmusante** [Nefelim4ag/Ananicy#100]
Request the option for a single file with all ".rules" integrated. I prefer if an ananicy-rules.conf or something similar could be created vice the creation of so many separate files that have to be parsed.

**Comment by Nefelim4ag** [comment]
How you see such option?
Magic button "ananicy write all files to one"?
And for what?

i.e. what the problem, you want solve?

**Comment by ryanmusante** [comment]
To merge all .rules into single rules file within it's subdirectory. Ease of implementation and ease of maintenance for a more streamlined application. Configuration is easier to change and/or move to a different location later. Also, doing a search for a specific rule can be done quicker.

I don't know if it is a problem, it just seems like an unorthodox way of operation to have multiple files.

**Comment by Nefelim4ag** [comment]
@ryanmusante 

Short answer:
 - Nope, one big file it's a big problem.
 - Many small files add some overhead, but that's easy to manage, easy to merge & etc

---

Long answer:
How long you are familiar with unix systems?

Many different things have such design (for decades), init.d, modprobe, modules-load, grub, systemd,
/etc/profile.d/, sysctl & many, many others.

Have one config, not a bad solution, but not support name.d to overwrite things - stupid.

Anyway, i need to support case, where someone add own rules to repo, if all rules will be stored in one file that will not be better, that will only bother with package maintaining and updating.

With current logic, anyone can create 99-overwrite, and rewrite all rules to something else, and update will not touch them.

What's mean by "easier to change"? you anyway need open files and change them.

Track what changed between releases, with one big file it's a hell.

We already have about 220 rules, add description to that, and you will get big file, which will be bigger with every new rule added, that a madness.

For search rules, and anything in string you have a plenty of unix tools, as ex:
```
~ grep -iR wine /etc/ananicy.d
```

- - - 

thanks.

**Comment by ryanmusante** [comment]
I've been working with Linux for many years but my experience with Python and scripting is rather short. I understand what you mean by the case with rules for the repository. I was just making a recommendation if it might be appropriate. How much overhead does each rule add to processing?

**Comment by Nefelim4ag** [comment]
@ryanmusante, with currently design:
find files with name mask
read line by line
parse to memory

So, that only startup overhead and it too small.
 - - -
In runtime:
Old ananicy store rule per file to use bash hacks like source file.rules
But by nature of using pgrep, we have:
O(m*n): where m count of rules, and n count of pids/threads

So crazy overhead, i.e. for processing one rule, we need full scan of proc - that's crazy stupid.
 - - -
With currently design:
Create /proc map, and use 'cmd' as a key for hash table with rule names.
So O(1) to process rule.
And O(n) to run ananicy.
 - - -
I didn't count operation to get/set nice, ioclass & etc.

**Comment by ryanmusante** [comment]
Version 2 is exponentially faster than version 1, there is no actual problem with speed.
