### ISSUE TITLE
Bug -- Processes listed in ps/top won't work from rules

### ISSUE THREAD

**Issue by ryanmusante** [Nefelim4ag/Ananicy#102]
After a recent system upgrade, some processes list python2 or python3 next to their command as in _/usr/bin/python2 /usr/bin/terminator_. 

Now _{ "name": "terminator","type": "LowLatency_RT" }_ won't call the process. 

What is the proper way to configure this in rules?

**Comment by Nefelim4ag** [comment]
No way currently, i've not implement that currently.
You can leave that open currently, i will close, when i've fix that.

**Comment by ryanmusante** [comment]
Status update for feature?

**Comment by Nefelim4ag** [comment]
@ryanmusante, sorry, nothing new

Currently i'm too busy to work on that

**Comment by Microeinstein** [comment]
@ryanmusante One temporary workaround I found, is to create an alias symlink [like busybox does] for each of your interpreted applications, and then edit their run scripts to use the aliases.

Example: [**Carla**](https://kx.studio/Applications:Carla) (/usr/bin/python3 /usr/share/carla/carla)
1. `ln /bin/python3 /bin/pycarla`
2. (edit `/bin/carla` to use `pycarla`)
3. create `carla.rules` with
```
{ "name": "pycarla", "type": "LowLatency_RT", "nice": -11, "sched": "rr" }
```

And it's done 👍🏻
