### ISSUE TITLE
Restarting the service does not show rule errors

### ISSUE THREAD

**Issue by CottonEaster** [Nefelim4ag/Ananicy#107]
My rules were in the old format. (Nothing had told me there was a new format!) Hence they failed. However, I realised this only when running `sudo ananicy dump proc`. For `sudo service ananicy restart` produced no error. Perhaps no error was display because I have the following in my `.conf`:

```
# Verbose msg: true/false
cgroup_load=false
type_load=false
rule_load=false

apply_nice=true
apply_ioclass=true
apply_ionice=true
apply_sched=true
apply_oom_score_adj=true
apply_cgroup=true
```

*Surely, though, errors should be logged even when ananicy is set not to report anything else*.

**Comment by Nefelim4ag** [comment]
@CottonEaster,
can't reproduce.
i.e. i created file with random content and disable verbosity, all works.

i.e. https://github.com/Nefelim4ag/Ananicy/blob/1.99.6/ananicy.py#L431

Exception handler doesn't hidden under if condition.
