### ISSUE TITLE
sudo ananicy dump proc produces an error

### ISSUE THREAD

**Issue by CottonEaster** [Nefelim4ag/Ananicy#108]
```
$ sudo ananicy dump proc
Traceback (most recent call last):
  File "/usr/bin/ananicy", line 716, in <module>
    main(sys.argv)
  File "/usr/bin/ananicy", line 712, in main
    daemon.dump_proc()
  File "/usr/bin/ananicy", line 660, in dump_proc
    self.update_proc_map()
AttributeError: 'Ananicy' object has no attribute 'update_proc_map'
```

Linux Mint 18.3 x64 Cinnamon. Ananicy ??. (I don't know how to get the version number for ananicy.)

**Comment by Nefelim4ag** [comment]
@CottonEaster,
yes, sorry, i forgot to push fix for that:
https://github.com/Nefelim4ag/Ananicy/commit/305513f95967330829cdf1f63790dff3c77f96da

**Comment by CottonEaster** [comment]
The ostensible fix does indeed fix the problem. Thank you.
