### ISSUE TITLE
The new(ish) Cinnamon rules look a bit aggressive . .

### ISSUE THREAD

**Issue by CottonEaster** [Nefelim4ag/Ananicy#110]
. . and I think they might be slowing down the speed with which keystrokes appear on my screen. Can you shed any light, please? 

By 'aggressive' (in my title) I mean: it seems that the Cinnamon rules mess with lots of rather fundamental Cinnamon processes.

**Comment by ryanmusante** [comment]
The original rules set came from this. Than I added the cinnamon-settings-daemons. Whatever your suggestions, I'm open. 

https://github.com/Nefelim4ag/Ananicy/issues/38

**Comment by CottonEaster** [comment]
Well, I don't understand any of the following very well: Cinnamon; the bug report you cited; ananicy. Yet, it seems that there is no special need for the Cinnamon ananicy rules (unless I misunderstand something in the aforementioned bug report). If there is indeed no special need for those rules, then, because the rules mess with low-level processes, I think it's best just to remove the rules. Certainly I'll be removing them on my system.

**Comment by ryanmusante** [comment]
It is because many of the window managers and desktop environments also have rules files generated. So I created cinnamon to give it higher priority.

**Comment by ryanmusante** [comment]
Changed rules file to less aggressive, very basic options.

**Comment by CottonEaster** [comment]
@ryanmusante 

I am sorry for not replying sooner to your penultimate post. Let me reply to most of it, as follows.

- My system specs: Lenovo X1 Carbon 6th Gen laptop (with quad processor); 16GB RAM; fast SSD.
- Cinnamon 3.6.7 running on Mint 18.3. (Mint hasn't got a later version of Cinnamon yet. The Mint people use users of non-Mint distros as guinea-pigs!)
- Had I updated to the newst ananicy? Yes.

I suspect that the making of the Cinnamon rules less aggressive is a good idea. I'll close this report.
