### ISSUE TITLE
[Feature Request] Setting cpu governor based on processes

### ISSUE THREAD

**Issue by terencode** [Nefelim4ag/Ananicy#122]
Basically, add something similar to what proposes [gamemode](https://github.com/FeralInteractive/gamemode).

**Comment by Nefelim4ag** [comment]
@terencode, i'm not sure what you mean, but ananicy already support changes of cpu schedulers.
https://github.com/Nefelim4ag/Ananicy/blob/4d45e78ad2efe880634f77b9e17ac8e227f0e05d/ananicy.d/00-default/wineserver.rules#L4

**Comment by terencode** [comment]
@Nefelim4ag my bad, I meant  cpu governor.

**Comment by Nefelim4ag** [comment]
IMHO, blindly change cpu governor to performance are cancer.
For that purpose, i.e. scale cpu based on some factors, linux have schedutil governor.

**Comment by Nefelim4ag** [comment]
@terencode, you has tested performance governor with jack and that helped?

**Comment by terencode** [comment]
@Nefelim4ag, yes, and that is what is recommended in any linux pro audio documentation.

**Comment by Nefelim4ag** [comment]
@terencode, i'm really not sure how to properly track when process are exits, and when that make sense to set governor back.
More, some people like am i use tools like tlp, and that doesn't possible to avoids conflicts on that ground.
