### ISSUE TITLE
Please consider adding the following to your wiki page

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [Nefelim4ag/Ananicy#13]
(1) How long it takes to apply a newly created rule, and whether one needs to restart the service to do so.

(2) The available IONICE values (`normal`, `idle` and `realtime`?)

Also (3) to submit a rule to you, I should use a 'pull request', yes?

Thanks.

**Comment by Nefelim4ag** [comment]
@ACinnamonUserInUK,
1. https://github.com/Nefelim4ag/Ananicy/commit/aa20210884d9ccf18f4f677b5ce71806358ef6fb, ananicy load rules while starting, so just restart the service
2. https://github.com/Nefelim4ag/Ananicy/commit/02d9e64c053ce0962eddfdd5708fa7f27c63fe21, so yes
3. https://github.com/Nefelim4ag/Ananicy/commit/b35fbbc55b2ebae29fea4e24e86e2bc2bf69ca93, so yes
