### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by CottonEaster** [Nefelim4ag/Ananicy#130]
From my logs:

![image](https://user-images.githubusercontent.com/9998846/46250225-2601ec00-c42e-11e8-96b6-57931e2f8a01.png)

Mint 19 x64 Cinnamon
Ananicy version: sorry, I deleted the installation files - but the github version from a few days ago.

**Comment by Nefelim4ag** [comment]
Sorry, i need full logs to fix something.

**Comment by CottonEaster** [comment]
[Here you go](https://gist.github.com/CottonEaster/558fbdb245c78e2cb3627d9cdc5d942d).
