### ISSUE TITLE
Default configuration for Steam is fundamentally broken

### ISSUE THREAD

**Issue by terencode** [Nefelim4ag/Ananicy#131]
See https://github.com/FeralInteractive/gamemode/issues/68#issuecomment-426730158

**Comment by Nefelim4ag** [comment]
Yep, that true.

**Comment by terencode** [comment]
Maybe the whole game part of ananicy config should be removed to let gamemode fully handle it?

**Comment by Nefelim4ag** [comment]
Not sure why "whole game", i.e. i did not see any problems with renice processes.
i.e. if steam process reniced - that cause some issues. So let's remove that stupid rule.

**Comment by terencode** [comment]
Ok then, closing.
