### ISSUE TITLE
Can I disable ionicing for schedulers on which it does not work?

### ISSUE THREAD

**Issue by CottonEaster** [Nefelim4ag/Ananicy#132]
I have many instances of the following in the log. I understand why, but I would like to stop Ananicy from trying to apply the scheduling.

`Disk nvme0n1 not use cfq/bfq scheduler IOCLASS/IONICE will not work on it`

Thanks.

**Comment by Nefelim4ag** [comment]
check:
https://github.com/Nefelim4ag/Ananicy/commit/a23b874b09c5c3823ba44d5d52dc91114a58b321

**Comment by CottonEaster** [comment]
Sweet.
