### ISSUE TITLE
Cinnamon wrong rules

### ISSUE THREAD

**Issue by fabiodellaria** [Nefelim4ag/Ananicy#133]
Using the current Cinnamon ruleset, there is a conflict where cinnamon-screensaver continually chnages between LowLatencyRT settings and BG_CPUIO settings.

Is this because of the prefix “cinnamon” is overriding anything with it in the whole word?

cinnamon.rules file:

> 
> NAME=cinnamon                   TYPE=LowLatency_RT
> NAME=cinnamon-session           TYPE=LowLatency_RT
> NAME=cinnamon-killer-daemon     TYPE=LowLatency_RT
> NAME=cinnamon-launcher          TYPE=LowLatency_RT
> NAME=nemo                       TYPE=LowLatency_RT
> NAME=cinnamon-screensaver       TYPE=BG_CPUIO
> NAME=cinnamon-slideshow.py      TYPE=BG_CPUIO

I suggest to change the first line with the following:

> NAME=^cinnamon$                 TYPE=LowLatency_RT

**Comment by ryanmusante** [comment]
Good idea. Recommend pull request.

**Comment by fabiodellaria** [comment]
Thanks a lot! :)

Fabio

Il giorno mer 10 ott 2018 alle ore 13:04 Ryan Musante <
notifications@github.com> ha scritto:

**Comment by Nefelim4ag** [comment]
Ananicy has been rewritten, so that can't be accepted upstream.

**Comment by fabiodellaria** [comment]
> Ananicy has been rewritten, so that can't be accepted upstream.

When will be available the new stable release?

**Comment by Nefelim4ag** [comment]
I forget what i want to implement from old functions, so... i can tag stable release in theory %)

**Comment by ryanmusante** [comment]
@fabiodellaria
This is what I had used as pull request, but change it to make it more efficient if needed.
```

# Cinnamon Desktop http://developer.linuxmint.com/

# Includes Cinnamon-Settings-Daemon plugins

{ "name": "cinnamon",			"type": "LowLatency_RT" }

{ "name": "cinnamon-session",		"type": "LowLatency_RT" }

{ "name": "cinnamon-killer-daemon",	"type": "LowLatency_RT" }

{ "name": "cinnamon-launcher",		"type": "LowLatency_RT" }

{ "name": "cinnamon-screensaver__ ",	"type": "BG_CPUIO" }
```

**Comment by LinuxOnTheDesktop** [comment]
I seem to have the rules mentioned in the post above - already. So, has this patch been merged? If so, should not the issue be closed?

**Comment by LinuxOnTheDesktop** [comment]
Sorry about this, but perhaps the rules above, which have been merged, are not the best. Here's why.

Just now, due seemingly to a bug in Cinnamon (that I can't easily reproduce and I'd rather not anyway; and it is somewhat relevant that I am using an alpha build of Cinnamon), Cinnamon was using more CPU than it should and the whole system was sluggish - even typing in Github text boxes such as this one. Yet, Cinnamon was using _only 7%_ of my CPU (on a 2018 quad-core Intel i7, with mitigations disabled).

Tentative inference: _the 'LowLatency_RT' in those rules needs to be replaced with something less aggressive_ (but I'm not sure what). At present, the rules are not fault-tolerant.
