### ISSUE TITLE
It is unclear how to use a pull request to submit new rules, at least if one haven't done a pull request before

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [Nefelim4ag/Ananicy#14]
Given the problem expressed by my title, I am putting my proposed rules here.

```
# Cairo-dock rules. Cairo-dock is a dock application; see https://www.glx-dock.org/
NAME=cairo-dock            NICE=-1
```

```
# Rules for clamav components. Clamav is a well-know antivirus for Linux.
NAME=clamtk NICE=-1
NAME=clamscan NICE=3 IOCLASS=best-effort IONICE=6
```

```
# Rules for Conky. Conky display system information on the desktop; https://github.com/brndnmtthws/conky
NAME=conky           NICE=1
```

```
# gdebi-gtk rules. Gdebi installs Debian packages.
NAME=gdebi-gtk NICE=1 IOCLASS=best-effort IONICE=5
```

```
# gnome-system-monitor. This monitor is used in many Linux distributions and in the Gnome desktop environment.
NAME=gnome-system-monitor            NICE=1
```

```
# Rules for systemback - a system restore program; https://sourceforge.net/projects/systemback/
NAME=systemback      NICE=0
```

**Comment by Nefelim4ag** [comment]
https://help.github.com/categories/collaborating-with-issues-and-pull-requests/
Long story, short:
1. You need do a fork of my repo (see button above)
2. GitHub will clone my repo to your account, and you will have tha same version of my repo
3. You do "git clone" repo to your machine
4. Make changes
5. git commit -am "New rules added" #or something like that
6. git push # this will copy commited data changes to your copy of my repo
7. In your repo click a button "New pull request"

Then i can review changes, and merge it, something like that

**Comment by ACinnamonUserInUK** [comment]
Well, this might be fun and useful to learn, but I find it a bit forbidding. That latter thing said, the steps that you were kind enough to provide seem admirably easy to follow, with the exception of 1. I'll see what I can do.

**Comment by Nefelim4ag** [comment]
I can already provide some feedback.

```
# gnome-system-monitor. This monitor is used in many Linux distributions and in the Gnome desktop environment.
NAME=gnome-system-monitor  NICE=1
```
I think as it's a similar to Task Manager on windows, it must have a more high priority.
So you can replace NICE=1 with TYPE=LowLatency_RT

---
```
# Rules for Conky. Conky display system information on the desktop; https://github.com/brndnmtthws/conky
NAME=conky           NICE=1
```
This depends of our point of view, if we think that Conky is a realtime system monitor, you can use: TYPE=LowLatency_RT
But if we think about conky like, it just a background system monitor, and it's can't interact with user, so then better use something like: TYPE=BG_CPUIO

---
```
# Rules for clamav components. Clamav is a well-know antivirus for Linux.
NAME=clamtk NICE=-1
NAME=clamscan NICE=3 IOCLASS=best-effort IONICE=6
```
I think it's better use TYPE=BG_CPUIO for NAME=clamscan, as it a just background task.

**Comment by ACinnamonUserInUK** [comment]
Thanks for those comments. Good stuff.

I had decided already that my Conky was too laggy with the setting that I had given in (viz, a niceness of 1). I will look up 'LowLatency_RT' and 'TYPE=BG_CPUIO'; I wasn't aware of those settings.

Lastly here: clamscan isn't a background task if one uses one's file manager to get clam to scan some particular (small-ish) item. Hmm.

**Comment by ACinnamonUserInUK** [comment]
Upon implementing your proposal for a rule for gnome-system-monitor allows that program to use 7 - 14% of my CPU. That was the problem - indeed, perhaps a worsening of the problem - that I was trying to solve in the first place! Hmm . .
