### ISSUE TITLE
ioprio_get failed: No such process error

### ISSUE THREAD

**Issue by ryanmusante** [Nefelim4ag/Ananicy#147]
This error occasionally shows in journalctl when loading or exiting applications. 

What am I doing wrong?
```
Mar 10 09:47:02 xmg ananicy[499]: ionice: ioprio_get failed: No such process
```

**Comment by Nefelim4ag** [comment]
@ryanmusante, if that not repeat too many times - don't see any problem.

i.e. ananicy cached state can be out of sync with system, that normal and some times, system app can be closed before ananicy end apply rules.

**Comment by LinuxOnTheDesktop** [comment]
Request: make ananicy log something like what you, ryanmusante, wrote above. That way, the user who reads the logs will not worry that ananicy is malfunctioning. Thanks.
