### ISSUE TITLE
Recommended archivers rules?

### ISSUE THREAD

**Issue by francoism90** [Nefelim4ag/Ananicy#148]
A lot of modules like lz4, gzip and lzma are used by filesystems, servers (VPN), etc.
I don't know if they use inbuilt modules or relay on the system provided bin.
Anyway, I was thinking of upper these numbers and still keeping everything 'nice':
```
{ "name": "bzip2", "type": "Heavy_CPU", "nice": 1, "ionice": 1 }
{ "name": "gzip",  "type": "Heavy_CPU", "nice": 1, "ionice": 1 }
{ "name": "lz4",   "type": "Heavy_CPU", "nice": 1, "ionice": 1 }
{ "name": "lzma",  "type": "Heavy_CPU", "nice": 1, "ionice": 1 }
{ "name": "lzop",  "type": "Heavy_CPU", "nice": 1, "ionice": 1 }
{ "name": "xz",    "type": "Heavy_CPU", "nice": 1, "ionice": 1 }
```
Also I was thinking about using `Heavy_CPU` as these will/may have impact on the CPU.

What are you thoughts?

Thanks.

**Comment by Thermi** [comment]
They are built in. They do not call other binaries to perform those functions.

**Comment by francoism90** [comment]
@Thermi Thanks and sorry for the noise. :)
