### ISSUE TITLE
Small installation problem, of late

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [Nefelim4ag/Ananicy#16]
As you can see from the below, I had to jump a hoop or two to get the most recent version installed (on Mint).

```
~ $ git clone https://github.com/Nefelim4ag/Ananicy.git /tmp/ananicy
Cloning into '/tmp/ananicy'...
remote: Counting objects: 512, done.
remote: Total 512 (delta 0), reused 0 (delta 0), pack-reused 512
Receiving objects: 100% (512/512), 88.11 KiB | 0 bytes/s, done.
Resolving deltas: 100% (248/248), done.
Checking connectivity... done.
~ $ sudo /tmp/ananicy/install.sh
[sudo] password for nicholas: 
sudo: /tmp/ananicy/install.sh: command not found
~ $ cd /tmp/ananicy
/tmp/ananicy $ ls
ananicy  ananicy.d  ananicy.service  LICENSE  Makefile  package.sh  README.md
/tmp/ananicy $ cp /home/nicholas/Ananicy/install.sh /tmp/ananicy
/tmp/ananicy $ ./install.sh
/tmp/ananicy $ sudo systemctl restart ananicy
Warning: ananicy.service changed on disk. Run 'systemctl daemon-reload' to reload units.
/tmp/ananicy $ sudo systemctl daemon-reload
```

Apologies if it is my mistake. By the way, I like your most recent commit: it well help keep my logs tidy.

**Comment by ACinnamonUserInUK** [comment]
Ah, it seems the command I want is:

sudo make install ananicy

I think you've changed your packaging without updating your instructions.

**Comment by Nefelim4ag** [comment]
@ACinnamonUserInUK, https://github.com/Nefelim4ag/Ananicy/commit/c56416f7626f897bf53bdcfe18ba59a5ea69f6c0

**Comment by ACinnamonUserInUK** [comment]
@Nefelim4ag

The point, I think, was that the website instructions still advocated the old method. However, I see that you've fixed that now. That's good.
