### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by lindroidux** [Nefelim4ag/Ananicy#165]
Jul 02 19:52:14 tsid ananicy[11050]: Load rules: /etc/ananicy.d/00-default/skype.rules
Jul 02 19:52:14 tsid ananicy[11050]: Load rules: /etc/ananicy.d/00-default/imagemagick.rules
Jul 02 19:52:14 tsid ananicy[11050]: Load rules: /etc/ananicy.d/00-default/google-chrome.rules
Jul 02 19:52:14 tsid ananicy[11050]: Traceback (most recent call last):
Jul 02 19:52:14 tsid ananicy[11050]:   File "/usr/bin/ananicy", line 773, in <module>
Jul 02 19:52:14 tsid ananicy[11050]:     main(sys.argv)
Jul 02 19:52:14 tsid ananicy[11050]:   File "/usr/bin/ananicy", line 754, in main
Jul 02 19:52:14 tsid ananicy[11050]:     daemon.run()
Jul 02 19:52:14 tsid ananicy[11050]:   File "/usr/bin/ananicy", line 692, in run
Jul 02 19:52:14 tsid ananicy[11050]:     self.process_tpid(tpid)
Jul 02 19:52:14 tsid ananicy[11050]:   File "/usr/bin/ananicy", line 675, in process_tpid
Jul 02 19:52:14 tsid ananicy[11050]:     rule_name = pe.stat_name
Jul 02 19:52:14 tsid ananicy[11050]:   File "/usr/bin/ananicy", line 77, in stat_name
Jul 02 19:52:14 tsid ananicy[11050]:     return line_list[1]
Jul 02 19:52:14 tsid ananicy[11050]: IndexError: list index out of range
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Main process exited, code=exited, status=1/FAILURE
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Failed with result 'exit-code'.
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Consumed 353ms CPU time.
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Service RestartSec=100ms expired, scheduling restart.
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Scheduled restart job, restart counter is at 7.
Jul 02 19:52:14 tsid systemd[1]: Stopped Ananicy - ANother Auto NICe daemon.
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Consumed 353ms CPU time.
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Start request repeated too quickly.
Jul 02 19:52:14 tsid systemd[1]: ananicy.service: Failed with result 'exit-code'.
Jul 02 19:52:14 tsid systemd[1]: Failed to start Ananicy - ANother Auto NICe daemon.

**Comment by Nefelim4ag** [comment]
https://github.com/Nefelim4ag/Ananicy/commit/e931d2d198b8e7b535fb5065317627a2d38e83fe
