### ISSUE TITLE
Feature - oom-killer score adjustment.

### ISSUE THREAD

**Issue by bartoszek** [Nefelim4ag/Ananicy#17]
Hi.
I was looking for a systematic way to adjust oom killer score for some crucial processes run on my system 
> sometimes i have like a mesh reconstruction job witch can take up to couple of hours and have peek memory consumption close to 20GB - witch i don't wont to get killed when i open google-chrome (which should have its oom_adj boosted to 10 at least)

...and I thought about annanicy which makes life easier for my HDD. Similar feature for RAM would be the oom-killer score adjustment. This could prevent someones blender job from being "canceled" because it's get less "score" than some leftover chrome tabs :(
regard.bartus

**Comment by Nefelim4ag** [comment]
@bartoszek, https://github.com/Nefelim4ag/Ananicy/commit/4e76e0c75efd62b09571fa32ca4d76e3d708d0f1
