### ISSUE TITLE
Ananicy will do nothing on Ubuntu or Mint?

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Nefelim4ag/Ananicy#172]
Thid report is not quite a bug report - although one might think that your documentation should reflect what I report.

There is some reason to think that most often on Ubuntu and Mint nicing will do nothing. Please see [this Reddit thread](https://old.reddit.com/r/linux/comments/d7hx2c/why_nice_levels_are_a_placebo_and_have_been_for_a/) and please advise. Thank you.

**Comment by Nefelim4ag** [comment]
Oh, you right, same on Archlinux and think many other systems.

**Comment by LinuxOnTheDesktop** [comment]
So . . what to do? I imagine that, if users on the affected distros are to continue to use ananicy - or rather to use it in a way that actually works - then either (1) they or ananicy will need to disable the behaviour that is preventing the nicing, or (2) you will need to change how ananicy operates. Please advise.

**Comment by Nefelim4ag** [comment]
Oh, i think what currently what only solution is to disable autogroup by ananicy
Because set niceness with aware of autogroup seems too complex for me currently.
I just have no idea how to merge autogroup with currently rules

**Comment by Nefelim4ag** [comment]
https://github.com/Nefelim4ag/Ananicy/commit/38eb4773b66f058e2960d735e90ee25a22be82c1

**Comment by LinuxOnTheDesktop** [comment]
Thanks. But . . might there be significant consequences of disabling 'autogroups'?

**Comment by Nefelim4ag** [comment]
@LinuxOnTheDesktop, i tested that for month, i didn't see any issues.
(But i have a powerful machines (i7 4/8 cores) - so, not sure about low spec hardware)
