### ISSUE TITLE
Cinnamon rules seem to set file manager and other applications to nice -10

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Nefelim4ag/Ananicy#181]
**The problem**

When I copied a large file I noticed this:

![image](https://user-images.githubusercontent.com/47056543/70368435-2f90aa80-18a2-11ea-9069-68dc2aa6549b.png)

It turns out that the 'Very High' niceness reported by that system monitor is niceness -10.

Now, my file-manager, Nemo, should not be at -10 niceness, because that's not sane and I have a Nemo ananicy rule to set it to nice 0. Nor should a lof of that other stuff be at -10. 

**Diagnosis**

Playing around seem to show that, if ananicy is running, restarting Nemo gives it a -10 niceness. I found that if I removed the (default) ananicy Cinnamon rules, the whole problem went away. Note that simply stopping anaicy does not solve the problem, if Cinnamon (or possibly `cinnamon-session` as against `cinnamon`) is at -10. This suggests that Cinnamon propagates its ananicy-assigned -10 niceness to programs that it (CInnamon) is involved in launching.

**Proposed remedy**

Trust distro developers to nice their rather critical comments. So: _just delete the Cinnamon rules_ and indeed issue a warning about creating any.

Ananicy: latest git, I think. (It would be nice were `ananicy --version` to work.)
Linux Mint 19.2 Cinnamon

**Comment by LinuxOnTheDesktop** [comment]
I take the liberty of bumping this issue. For, it seems a rather critical one - comparable to #177.

**Comment by LinuxOnTheDesktop** [comment]
This problem persists. Indeed on my systems just now it has meant that the indexer of the launcher program 'Albert' got niced to -10. _Not_ good.

**Comment by Nefelim4ag** [comment]
You can just create PR and remove them, if they perform bad.

**Comment by LinuxOnTheDesktop** [comment]
I tried and I got into terrible trouble with git; I am unused to doing more than fetching with it. When don't you just please delete the cinnamon.rules file?
