### ISSUE TITLE
warning > 'return' - only from function or script.

### ISSUE THREAD

**Issue by bartoszek** [Nefelim4ag/Ananicy#19]
I got bunch of those warnings reported to system journal.
`/usr/bin/ananicy: line 267: return: exit by `return' possible only from function or script`
Ananicy works correct despite those warnings.

**Comment by Nefelim4ag** [comment]
@bartoszek, https://github.com/Nefelim4ag/Ananicy/commit/96baebb762e0a3fad031b760b20969ce25ed2fd4
