### ISSUE TITLE
[basic] are all rules active by default?

### ISSUE THREAD

**Issue by greenisagoodcolor** [Nefelim4ag/Ananicy#197]
Cool software! Are all rules in /etc/ananicy.d/00-default active by default? Or do I have to modify each rule.

E.g. default mailspring
`# https://getmailspring.com
{ "name": "mailspring", "type": "Chat" }
{ "name": "mailsync", "type": "BG_CPUIO" }
{ "name": "mailsync.bin", "type": "BG_CPUIO" }
`

Do i need to modify each line according to readme schema?
`{ "name": "gcc", "type": "Heavy_CPU", "nice": 19, "ioclass": "best-effort", "ionice": 7, "cgroup": "cpu90" }
`

So I would have to add nice, ioclass, ionice, and c group to the three mailspring lines above?

Thank you,
Matt

**Comment by Nefelim4ag** [comment]
I suggest you to just try dump loaded rules: `~ sudo ananicy dump rules`
I think that will help you =)

**Comment by greenisagoodcolor** [comment]
Thank you! Solved.

**Comment by Nefelim4ag** [comment]
@greenisagoodcolor 
You can't directly copy-paste rules from dump rules of course, but you don't need it
dump rules just print ALL loaded rules, with all possible values (i.e. null if nothing set).

So when you write your rule and want to understood how ananicy parse it, you can restart daemon and get dump new dump.
