### ISSUE TITLE
How to autoupdate on ubuntu?

### ISSUE THREAD

**Issue by Salekin-1169** [Nefelim4ag/Ananicy#199]
I've installed **Ananicy** on ubuntu 20.04 manually by
`sudo make install`

as far as I know, this will not be auto-updated and my installation will always be the version i pulled from github before setup.

Is there any way to auto-update? Or  do I need to uninstall and reinstall again (build from source).

Thank you. :bow:

**Comment by Nefelim4ag** [comment]
just `make install` will be enough for update,
no autoupdate feature, i.e. in general ananicy must be packaged by someone

**Comment by Salekin-1169** [comment]
closing because of answer has been provided :bow:
