### ISSUE TITLE
Excessive logging

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [Nefelim4ag/Ananicy#20]
Sorry to raise this in the form of an 'issue', but I couldn't see how else to get help.

Ananicy logs all the adjustments it makes, in the main system log, and in my log those recordings are getting a bit out of hand. How to tell Ananicy to log only errors? Thanks.

**Comment by Nefelim4ag** [comment]
Test it: https://github.com/Nefelim4ag/Ananicy/commit/c04c7aa316e726a954ff8028e30b871c17bd426c

**Comment by ACinnamonUserInUK** [comment]
Seems goot to me!
