### ISSUE TITLE
Slow shutdown

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [Nefelim4ag/Ananicy#22]
When my computer shutsdown, and I make the shutdown process visible, I see that Ananicy takes a couple of seconds to shut down. I'd like to speed up my shutdown (which, on my admittedly fairly underpowered, but lean computer, takes seven to fifteen seconds); so, can anything be done about this, please? Thanks.

Ananicy 1.3.0

Linux Mint 18.1 Serena x86_64
Kernel: 4.10.0-20-generic

**Comment by Nefelim4ag** [comment]
https://github.com/Nefelim4ag/Ananicy/commit/29a505e101f84dea90f36f86d2737b8e352d8037
Try change CHECK_FREQ to ~1s (Ananicy already CPU limited so i think this must not add heavy impact to your system)

**Comment by Nefelim4ag** [comment]
https://github.com/Nefelim4ag/Ananicy/commit/6cacf27281f08a62ca3bfdbeee5a5afaf04d98de
I think this will fix your issue

**Comment by ACinnamonUserInUK** [comment]
Thanks a lot. I am testing the revised code.

**Comment by ACinnamonUserInUK** [comment]
The problem seems to be solved. Thank you very much.

**Comment by LinuxOnTheDesktop** [comment]
Hello! My system sometimes stalls for ten or twenty seconds upon shutdown - and I see this in my logs:

`ananicy.service: Consumed 2min 19.750s CPU time`

Might ananicy be the thing holding up shutdown? Thanks.
