### ISSUE TITLE
Transmission rules

### ISSUE THREAD

**Issue by Haron-Prime** [Nefelim4ag/Ananicy#24]
Add these rules, please

> NAME=transmission-remote   TYPE=BG_CPUIO
> NAME=transgui              TYPE=BG_CPUIO
> NAME=transmission-cli      TYPE=BG_CPUIO

Regards.

**Comment by Nefelim4ag** [comment]
@Haron-Prime, https://github.com/Nefelim4ag/Ananicy/commit/45564627931ba4ae578653aa2998dc5264bffbf6

**Comment by Haron-Prime** [comment]
Thx
