### ISSUE TITLE
Single config file to enable/disable specific preferences.

### ISSUE THREAD

**Issue by MrLokans** [Nefelim4ag/Ananicy#3]
It may be inconvenient for the user to have all of the settings enabled all of the time, as well as delete them manually after every single update. So it seems to me that a config file should be present to enable or disable certain preferences, e.g. something like

```bash
# /etc/ananicy.conf
[global]
ignored=00-skype,00-xz
```

**Comment by Nefelim4ag** [comment]
I prefer, have system designed to manage config files by priority, i.e.:
What about have a directory like:
`/etc/ananicy.d/00-Configs/`
For internal parameters for ananicy
Values from this dir, can be overwriten below in any other folder, as example:
`/etc/ananicy.d/01-Custom_config/`

**Comment by francoism90** [comment]
Going to test Ananicy. :)

Instead of creating multiple files, it is possible to simple call more than one process in `NAME=`?
Now a rule needs to be created for each video-player (e.g. VLC, SMPlayer ..), but they share the class.
Same for other apps that should mostly share the same config.

Thanks!

**Comment by Nefelim4ag** [comment]
@MrLokans, in ananicy code, pgrep used for getting pids of processes
pgrep AFAIK can work only with process names

But you can just create one file, and create several rules by copy-past

**Comment by MrLokans** [comment]
This idea about classes is great, but it's better to be implemented in a different manner: we could have separate folder called something likes classes where we could define custom classes with their own priorities and if out config files reference them to inherit those value. (something similar to roles in ansible)

What I mean may be illustrated by the following scheme:
```
# classes.d/video-player.conf
NICE=-3     IOCLASS=realtime

# 00-Default/00-vlc.conf
NAME=vlc CLASS=video-player

**Comment by Nefelim4ag** [comment]
@MrLokans, now https://github.com/Nefelim4ag/Ananicy/commit/544c252b00c1348dc175cedec4ba5a16c9b374b5
You can disable rules for specific programs,

> $ cat /etc/ananicy.d/99-ignore.conf
> NAME=xz
> NAME=vlc

**Comment by francoism90** [comment]
@Nefelim4ag what about apps sharing the same class? e.g. VLC, SMPlayer, etc. It seems a rule needs to be written for each app?

Thanks :)

**Comment by Nefelim4ag** [comment]
This depend on which class system you want:
* If you want classes from Window Manager i.e. "Show me pids of all running media players at now"- i can't get it -> i can't use it
* If you want classes like @MrLokans suggest, it's more easy to implement, but in any way, rule per app will be needed.

So if i understand you correctly, at now needs rule must be written for each app
