### ISSUE TITLE
Disabling logging - is it broken?

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [Nefelim4ag/Ananicy#31]
With a recent build (built from git) - but also, perhaps, with earlier builds - the following config

```
## Ananicy configuration
CHECK_FREQ=0.2s

## Logging
INFO_MSG_NICE_ENABLED=false
INFO_MSG_IOCLASS_ENABLED=false
INFO_MSG_IONICE_ENABLED=false
INFO_MSG_SCHED_ENABLED=false
INFO_MSG_OOM_SCORE_ADJ_ENABLED=false
```

does not prevent much

> INFO: Parse /etc/ananicy.d/vlc.rules

and the like from occuring in my logs, when I do

    sudo systemctl restart ananicy

Is that as it should be?

Linux Mint 18.1 x64 Cinnamon.

**Comment by Nefelim4ag** [comment]
@ACinnamonUserInUK, yes it's work as designed

**Comment by ACinnamonUserInUK** [comment]
Ah, because there is no configuration option of the following form?

`INFO_MSG_PARSE_COMPLETED=false`

**Comment by Nefelim4ag** [comment]
https://github.com/Nefelim4ag/Ananicy/releases/tag/1.12.0
