### ISSUE TITLE
TVHeadend rules

### ISSUE THREAD

**Issue by francoism90** [Nefelim4ag/Ananicy#32]
Could you please add TVHeadend rules? This may help against stutter. :)

Thanks.

**Comment by Nefelim4ag** [comment]
@francoism90, as i not use TVHeadend i can't just write and add rule =)
But in theory (if i understand correctly what you get stutters with TVHeadend), test this:
```
NAME=tvheadend TYPE=PLAYER_VIDEO
# or
NAME=tvheadend TYPE=LowLatency_RT
```

**Comment by francoism90** [comment]
@Nefelim4ag Will try and report back. :)
