### ISSUE TITLE
Rules match based on any argument

### ISSUE THREAD

**Issue by pyamsoft** [Nefelim4ag/Ananicy#35]
_steam.rules contains a line which matches for the `Planetary Annihilation` game  
by searching for the name `PA`

On my system, a couple of scripts run with an argument like `PATH=...` which is how I came  
to notice this strange behavior.

Commands which run with any kind of argument looking like `...PA...` will match with the  
_steam.rules file and be run under `TYPE=GAME` incorrectly. This is because `pgrep -f -w PA`  
matches any command whose full name includes the text `PA` anywhere in it.

This can be most easily observed with the following:
```
[in one terminal]
$ vim PATH

[in another terminal]
$ pgrep -f -w PA
```
Ananicy will also log to the system journal that it is setting nice levels to -5 for the random vim process.

I have fixed this on my system by changing the `PA` line in `_steam.rules` to `^PA$` but I am  
unsure if this has any negative side effects since I do not actually run Planitary Anihilation.

**Comment by Nefelim4ag** [comment]
@pyamsoft,
i think that i've fix that:
https://github.com/Nefelim4ag/Ananicy/commit/533831293fc275c50c65cbbbb0dbfe5e01e21363

**Comment by pyamsoft** [comment]
The original issue appears to be fixed.

As a follow up, related issue, I've noticed this issue happens with effectively any profile.

For example, if I open a file in `$EDITOR` which is named as any program, it incorrectly adopts the nice level.

`$ vim cmake` adopts the cmake profile of nice 19, best-effort ionice 7.
`$ nano i3` adopts the i3 profile of low latency.

I believe this is because `pgrep -f` matches the command to any point in the name.

Please let me know if you want to continue in this issue or open a new one.

**Comment by pyamsoft** [comment]
It appears that for your original fix for PA, it does fix the issue, but I don't think it would properly trigger on `PA` anymore.

I believe you may have an extra `/` character in your regex.

**Comment by terencode** [comment]
@Nefelim4ag during startup: /usr/bin/ananicy: ligne 83: RULES_CACHE_TMP/.*/PA .*.rule: No file or folder of this type

**Comment by Nefelim4ag** [comment]
@terencode,
https://github.com/Nefelim4ag/Ananicy/commit/d5ba2ddfa0ce2a238a222ba241ebdc0378c0a832

**Comment by terencode** [comment]
@Nefelim4ag yup, fixed since this commit. Shouldn't this issue be closed now?

**Comment by Nefelim4ag** [comment]
Thanks!
