### ISSUE TITLE
Can't start the service on Raspbian last version

### ISSUE THREAD

**Issue by manuti** [Nefelim4ag/Ananicy#36]
I can install and use before Ananicy but with the last version this is the result I obtain when I'm going to strart the service:

```
$ sudo systemctl enable ananicy
$ sudo systemctl start ananicy
Job for ananicy.service failed. See 'systemctl status ananicy.service' and 'journalctl -xn' for details.

```

Yes is a Raspberry but the OS in the end is a modded Debian:

```
uname -a
Linux raspberrypi 4.9.28-v7+ #998 SMP Mon May 15 16:55:39 BST 2017 armv7l GNU/Linux

```

and

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

```

Any idea about how I can't resolve this?

Thanks

**Comment by Nefelim4ag** [comment]
I can't help without log output.
```
journalctl -efu ananicy
```
```
~# ananicy start
~# bash -x ananicy start
```
i think this can help you.

**Comment by manuti** [comment]
nothing happens
how I can send you a log related to the issue I'm having?
thanks

2017-07-08 20:40 GMT+02:00 Timofey <notifications@github.com>:

**Comment by Nefelim4ag** [comment]
@manuti, nefelim4ag@gmail.com or you can leave it in the issue as a code

**Comment by CottonEaster** [comment]
I had the same error just now on a computer with Mint installed.

`~# ananicy start`

(which is from a root prompt, note) produced

`ERRO: Missing schedtool!`

Doing

`~# apt install schedtool`

fixed the problem.

**Comment by Nefelim4ag** [comment]
Reopen if problem exists
