### ISSUE TITLE
Disabling ananicy for some child processes... aka garbled vim display?

### ISSUE THREAD

**Issue by nick-s-b** [Nefelim4ag/Ananicy#38]
Hi,
I've been using Ananicy for a while and had no issues. Recently, I made up some rules for my DE processes to give them real-time nice. However, that meant that every child started by the DE received real-time nice as well. So my terminal program received real-time nice and then vim received them as well.

Now, when I edit files with vim, my status bar and display is completely garbled because anancy is applying nice and for some reason the message is being sent to the terminal session. After I quit vim, I see something like `home/fairw/.zlogin:9: nice(5) failed: success`.

Anyone have any ideas how to fix this? Thank you!

**Comment by Nefelim4ag** [comment]
Looks strange, did you run ananicy as system (not user) systemd.service?
Not as user?

May be steps how to reproduce

**Comment by nick-s-b** [comment]
Hi!
Yes, I believe it runs as a system service. It's a default Arch install... I did not mess with it. Only thing I did was to add my own ruleset.

````
systemctl status ananicy
● ananicy.service - Ananicy - ANother Auto NICe daemon
   Loaded: loaded (/usr/lib/systemd/system/ananicy.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-09-14 10:57:19 EDT; 2h 47min ago
 Main PID: 509 (ananicy)
    Tasks: 2 (limit: 4915)
   Memory: 11.6M (high: 16.0M max: 64.0M)
      CPU: 20min 39.776s
   CGroup: /system.slice/ananicy.service
           ├─ 509 /bin/bash /usr/bin/ananicy start
           └─9089 sleep 0.2s
````

My cinnamon.rules:
````
cat cinnamon.rules
# Cinnamon Window Manager
# https://github.com/linuxmint/Cinnamon/
NAME=cinnamon                   TYPE=LowLatency_RT
NAME=cinnamon-session           TYPE=LowLatency_RT
NAME=cinnamon-killer-daemon     TYPE=LowLatency_RT
NAME=cinnamon-launcher          TYPE=LowLatency_RT
NAME=nemo                       TYPE=LowLatency_RT
NAME=cinnamon-screensaver       TYPE=BG_CPUIO
NAME=cinnamon-slideshow.py      TYPE=BG_CPUIO
````

When I start vim, it clearly gets the -10 nice from zsh. I don't have either vim or zsh in my rules.

![https://i.imgur.com/Akwvgzl.jpg](https://i.imgur.com/Akwvgzl.jpg)

And for some reason, nice output ends up in my vim session and it messes up text display.

Let me know if I can provide anything else and thank you for reading and help :)

**Comment by nick-s-b** [comment]
I did some more research. This message, `/home/nsb/.zlogin:9: nice(5) failed: success` happens only when I use vim. When I run nano, nothing happens. I even added a rule for vim in `vim.rules` and restarted anancy but the message still shows up. I don't know why.

**Comment by nick-s-b** [comment]
Finally had some time to trace down the issue and it seems that the problem was with vim, not with ananicy!

I've had few execute calls in vimrc and even though they had "silent!" parameter, they were catching stuff from the terminal. Solved it by adding `... >/dev/null 2>&1" | redraw!` at the end of the execute.

Thanks!
