### ISSUE TITLE
Reducing verbosity?

### ISSUE THREAD

**Issue by nick-s-b** [Nefelim4ag/Ananicy#39]
Hi all,
My journal is full of ananicy "INFO" messages. Is there a way to suppress those and only show errors?
Thanks!

**Comment by Nefelim4ag** [comment]
Check: https://github.com/Nefelim4ag/Ananicy/issues/31

**Comment by nick-s-b** [comment]
@Nefelim4ag Nice! No more info messages. Thanks!
