### ISSUE TITLE
'FileNotFoundError: [Errno 2] No such file or directory: '/proc/1447210/exe''

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [Nefelim4ag/Ananicy#428]
![image](https://user-images.githubusercontent.com/47056543/135734205-57aa6c68-8038-4c9c-8802-9c76a88cbdae.png)

```
$ ananicy --version
[No output; but my version is a recent version pulled from github]
```

Linux Mint 20.2 Cinnamon

**Comment by LinuxOnTheDesktop** [comment]
So, is this issue fixed in the latest release (version 2.2.1 of 29th January)?

**Comment by izissise** [comment]
It should be, have you tested if you're still having this issue?

**Comment by LinuxOnTheDesktop** [comment]
I think it is solved; I think I had not updated one of my installations. If the problem re-occurs, I shall ask for this issue to be re-opened. Thanks.
