### ISSUE TITLE
Power drain/high CPU usage as reported by PowerTOP

### ISSUE THREAD

**Issue by skmkenn** [Nefelim4ag/Ananicy#58]
When running Ananicy on an Intel Core i7-3610QM (8 threads) notebook PC, PowerTOP shows higher CPU usage when the machine is otherwise idle leading to increased power usage. Is there anything that can be done to make this more efficient?

**Output with Ananicy running:**
```
Summary: 959.4 wakeups/second,  0.4 GPU ops/seconds, 0.0 VFS ops/sec and 20.0% CPU use
2.72 W    234.8 ms/s     205.2        Process        ananicy
```

**Output after stopping Ananicy (systemctl stop ananicy):**
`Summary: 338.6 wakeups/second,  0.5 GPU ops/seconds, 0.0 VFS ops/sec and 4.8% CPU use`

**Comment by Nefelim4ag** [comment]
@skmkenn try that,
```
sudo sed -i 's/0.2s/1s/g' /etc/ananicy.d/ananicy.conf
```

**Comment by skmkenn** [comment]
Changing the check frequency in ananicy.conf has helped greatly, thanks for the help 👍

**Comment by allanlaal** [comment]
even with `check_freq=5` on a **server**, ananicy had been using up a huge amount of CPU %
