### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by In-line** [Nefelim4ag/Ananicy#67]
@Nefelim4ag 
https://github.com/Nefelim4ag/Ananicy/blob/4238e5eb97dd9ba18b976dfb50bda33d45a26926/ananicy.d/00-default/wine/LeagueOfLegends.rules#L5

**Comment by Nefelim4ag** [comment]
@In-line, nope, afaik, that a real name of binary.

But for now, that rule must be disabled, as i don't know if that works now.
Will be deleted, thanks.
