### ISSUE TITLE
Regression: Steam rules not working

### ISSUE THREAD

**Issue by terencode** [Nefelim4ag/Ananicy#69]
When a game included in *_steam.rules* starts, it does  `Process steam[10430] cpu nice: -5 -> 19` instead of apply a negative nice value to the game process.
I bisected the commit introducing the regression: 5e83682872672aef4f73d1a1e950a37601303769

**Comment by Nefelim4ag** [comment]
@terencode, which game?
That code only make some rules checks much more rare.

And logs show, that it change priority of stream process, not a game, processes on unix have Inherit the nice and other stuff.

**Comment by terencode** [comment]
I first thought this was just some new log format but when I checked the nice value of the game, it was the default one. I then figured out it was working before applying this commit. 
The game is Natural Selection 2.

**Comment by Nefelim4ag** [comment]
```
~# sudo ananicy dump rules | grep ns2_linux
RULES_CACHE_RARE/7e4264e0e7ab26807e6189531009a34e.rule:NAME=ns2_linux               TYPE=GAME                   TYPE=GAME           NICE=-5
```
That will mean nothing match the rule.

Also try that:
https://github.com/Nefelim4ag/Ananicy/commit/21eed65d11aba48181015fc264b9c8db6ebdca98

**Comment by terencode** [comment]
@Nefelim4ag Ok I investigated more:

1- It seems that after 5e83682, it was still able to set the nice value for the game, but it was spamming it between steam and the game process.

2- What made me not realize it was that the nice value is applied around 3mn after the game started (expected behavior with refresh set to 0.2?).

3- With 21eed65, it's not spamming nice value reset of steam and steamwebhelper when finding the game process.

**Comment by Nefelim4ag** [comment]
1. Hooray, i was right.
2. Nope, https://github.com/Nefelim4ag/Ananicy/commit/5e83682872672aef4f73d1a1e950a37601303769, try save cpu time on non check the rules that don't find anything.
May be that must be tuned.
3. Hooray, we need more PGREP_ARGS in rules, to strictly matching

**Comment by terencode** [comment]
With 3281acb, time elapsed before applying nice value went from 1mn30 to 30 seconds: much better.
Could this be somehow configurable because it's weird you can specify the frequency of the checks but it doesn't apply to this case.

**Comment by Nefelim4ag** [comment]
@terencode , like that?
https://github.com/Nefelim4ag/Ananicy/commit/757b0d072a2acd37820f360fdab58a7c06882524

**Comment by terencode** [comment]
Looks good!
