### ISSUE TITLE
Guidelines for .rules

### ISSUE THREAD

**Issue by droserasprout** [Nefelim4ag/Ananicy#7]
I think we need to list used values used for various categories of apps in README. It will be easier to add new rules and also to migrate from another renice daemon or custom script.

**Comment by Nefelim4ag** [comment]
Sorry, at now i don't have a clear view of "categories", so if you want/have idea about that
pull request are always welcomed =)

**Comment by Nefelim4ag** [comment]
Fisrt try:
https://github.com/Nefelim4ag/Ananicy/commit/e85472ae4371c9509f1ba06eedc8a50142bb0770

**Comment by Nefelim4ag** [comment]
@droserasprout, second try:
https://github.com/Nefelim4ag/Ananicy/commit/739d83b092431c44a27744d9337dce168b97afa1
https://github.com/Nefelim4ag/Ananicy/commit/4238e5eb97dd9ba18b976dfb50bda33d45a26926
