### ISSUE TITLE
Ananicy is slow and drains battery

### ISSUE THREAD

**Issue by teneri66** [Nefelim4ag/Ananicy#73]
Ananicy is slow and drains battery. Is 0.2s CHECK_FREQ default parameters really expected/required? Won't 15s or 30s do fine for most setups?

**Comment by Nefelim4ag** [comment]
@teneri66, slow? What you mean by that?
---
Battery usage and frequency:
 i think you need first look at:
 - https://github.com/Nefelim4ag/Ananicy/issues/69
 - https://github.com/Nefelim4ag/Ananicy/issues/58
---
0.2s it's a pause between check next rule, currently we have 171 rules, i.e. with 30s check freq, all checks will done only after ~1,5h.

May be that make a sense to change default to something less aggressive, like 0.5s

As now ananicy have 2 threads, one for rare checks and one for often, you can safely set that value to something like 1s..4s. More can cause problems for move logic between rare/often threads.

On my machine i have about ~16 rules in often threads, so 1s..2s, will also work "cool" for me.
But your case may differ. 

```
~$ sudo ananicy dump rules | grep OFTEN | wc -l
```

Thanks.
