### ISSUE TITLE
Blank spaces in file names for settings in ananicy file

### ISSUE THREAD

**Issue by ryanmusante** [Nefelim4ag/Ananicy#83]
Example NAME=Windows File.exe

Should it be NAME=Windows\040File.exe
NAME=Windows%20File.exe
NAME=Windows\ /File.exe

Or will NAME=Windows.exe cover everything with the prefix?

**Comment by Nefelim4ag** [comment]
Depends on your need.
By default NAME=Windows.exe will match any process where string contain that sub string.
