### ISSUE TITLE
Disk scheduler not used cfq/bfq warning

### ISSUE THREAD

**Issue by ryanmusante** [Nefelim4ag/Ananicy#84]
Both drives are set to deadline scheduler. Should this warning message be ignored? Is it deprecated from earlier version?

`"WARN: Disk sda not used cfq/bfq scheduler IOCLASS/IONICE will not work on it!"`

**Comment by Nefelim4ag** [comment]
@ryanmusante, that message mean that it mean, not more, no less.
If you don't need disk io priority scheduling - ignore.
