### ISSUE TITLE
Feature Request Addition to Repositories

### ISSUE THREAD

**Issue by ryanmusante** [Nefelim4ag/Ananicy#85]
In my opinion, this utility should be in most distributions main repositories. 

It is not just for convenience but in many cases, necessity. 

What does it take for this to happen?

**Comment by Nefelim4ag** [comment]
@ryanmusante, for that you need to talk with some guys, not with me.
Example:
 - For Ubuntu - Likely first try get in Debian.
 - For Debian - https://wiki.debian.org/DebianMentorsFaq
 - For RPM based distros - didn't know.
 - For Arch & co, it's already on AUR, to gen in main repo, some trusted users must be interested in this and package that for community repo.
 - & etc

i.e. to get package in some distribution repos, that a lot of bureaucracy work.
And i have not a spare time to speak with lot of different people on mailing lists.
