### ISSUE TITLE
Suggestion f

### ISSUE THREAD

**Issue by CottonEaster** [Nefelim4ag/Ananicy#86]
Much of the current text is hard to understand and (/because) not the best English. I suggest that you change

> Ananicy Rare/Often Frequency scaling
> Ananicy have 2 threads, if nothing match rule for 5 Min
> Rule moved to low requency check thread (rare)
> If rule from RARE thread match something,
> it's moved to OFTEN thread

to the following.

> On the frequency with which Ananicy performs its checks
> -------------------------------------------------------------------------------
> Ananicy has two threads. Each thread checks whether any process matches Ananicy's rules.
> However, one thread - the *often* thread - checks regularly
> (namely, at the time specified by the CHECK_FREQ variable, above).
> The other thread - the *rare* thread - checks much less frequently.
> All rules begin on the *often* thread.
> If a rule matches no process for five minutes,
> then that rule is demoted to the *rare* thread.
> If a rule running within the *rare* thread matches a process,
> then that rule is restored to the *often* thread.

One could elaborate the above text so as to explain, or begin to explain, the other comments in the conf file.

EDIT: Sorry for the title of this comment; I pressed return by accident.

**Comment by Nefelim4ag** [comment]
@CottonEaster, you are free to send PR.

**Comment by CottonEaster** [comment]
I would, but I don't know how.

**Comment by Nefelim4ag** [comment]
@CottonEaster,
you can open any file and use edit button. GitHub will do other boring things.
https://github.com/Nefelim4ag/Ananicy/edit/master/README.md

**Comment by CottonEaster** [comment]
OK, I think I've managed to work it out . . I have edited some of the comments in the .conf file. I would edit more, but I do not sufficiently understand what they mean, and so I am hesitant.

**Comment by Nefelim4ag** [comment]
You can ask inline in any file on my repo (because if you do that on your fork, i will not see notification).
