### ISSUE TITLE
[Discussion] Process binding on specific CPU cores

### ISSUE THREAD

**Issue by terencode** [Nefelim4ag/Ananicy#89]
I read https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_for_real_time/7/html/tuning_guide/interrupt_and_process_binding and I'm wondering if there is an interest in binding processes to specific CPUs with Ananicy. What about irqbalance? Woudln't it benefit regular non time-sensitive applications?

**Comment by ryanmusante** [comment]
Currently a script like this is necessary but it would be nice if it could be included with ananicy to automatically bind particulars to cpus.
```
pid=$(pgrep -x task.exe)
taskset -cp 2,4,6 $pid
```

**Comment by Nefelim4ag** [comment]
That not a problem with implement rule handler, which will bind some pid to some CPU.
Main "problem" with that, everyone who want use it, must write a rule for that.

**Comment by ryanmusante** [comment]
True, if it was default, it would become a problem for others.

**Comment by terencode** [comment]
Aren't their some configuration that makes sense for everyone? What about binding games to the first cores up (until number of cores / 2) ? And I'd like to know when using irqbalance makes sense because I have still mixed feelings about it. To me it looks like it's nice for regular apps but should be avoided for RT stuffs (music, games..) so what would be convenient to do?

**Comment by Nefelim4ag** [comment]
May be just add cgroup support?

I think about add something like:
Create cgroup name N
Change cpu share 1024 -> 512
And move noisy processes to that cgroup.

If i understood correctly, that will allow use up to 100% of cpu, if no other tasks use cpu,
and restrict cpu usage down to 50%, if someone others are hungry.

**Comment by Nefelim4ag** [comment]
i.e. irqbalance are cool, but i don't think that general home system/notebook have really much IRQ like some busy servers with big links have.

Cpu bind, which problem bind will fix?
Without some magic (tickless NOHZ), kernel will reschedule app on every HZ.

I can miss something of course, just my thoughts.

**Comment by Nefelim4ag** [comment]
Sad, but CPUShares not work as i expect.
Any way, we have a cpuset cgroup and cpu accounting cgroup,
first can move processes to specific CPUs, last can restrict max cpu usage for processes in cgroup.

**Comment by Nefelim4ag** [comment]
@terencode,
I can add some cgroup controlling code, which will restrict cpu usage of processes. If you think what that will be useful.

Also you can play with:
/sys/fs/cgroup/cpuset and others cgroup controllers, and add suggestion, if you found some of them are useful.

Thanks.

**Comment by terencode** [comment]
Thanks for the thoughts, I think what you implemented is already enough for the average user.
As you said, the rest would probably only benefit for servers...
