### ISSUE TITLE
Rules not being applied anymore

### ISSUE THREAD

**Issue by terencode** [Nefelim4ag/Ananicy#90]
It only works for ananicy itself but nothing is applied for all the other programs.
I tried reverting to an old version but it's not working, making me thinking it's something with my system.
The log is clean, I see at start
>avril 15 16:27:43 terence-arch systemd[1]: Started Ananicy - ANother Auto NICe daemon.
avril 15 16:27:43 terence-arch ananicy[22006]: INFO: Start main process
avril 15 16:27:44 terence-arch ananicy[22006]: INFO: Process ananicy[22006] ioclass: none  -> idle
avril 15 16:27:44 terence-arch ananicy[22006]: INFO: Process ananicy[22006] sched: normal -> idle
avril 15 16:27:44 terence-arch ananicy[22006]: INFO: Process ananicy[23791] ioclass: none  -> idle
avril 15 16:27:44 terence-arch ananicy[22006]: INFO: Process ananicy[23791] sched: normal -> idle
avril 15 16:27:44 terence-arch ananicy[22006]: INFO: Process ananicy[23792] ioclass: none  -> idle
avril 15 16:27:44 terence-arch ananicy[22006]: INFO: Process ananicy[23792] sched: normal -> idle

but that's it, nothing else.
I tried to do `sudo ananicy dump rules && sudo ananicy dump types` but it did nothing.

**Comment by terencode** [comment]
@ryanmusante makes sense, hope it will be easy to figure out what's wrong.

**Comment by Nefelim4ag** [comment]
@terencode, did you install the latest git version?

**Comment by terencode** [comment]
@Nefelim4ag Yup. I tried to git bisect but it's not working as it seems to not be a regression introduced by ananicy but rather something in my system.

**Comment by Nefelim4ag** [comment]
@terencode,
may be you have empty /etc/ananicy.d/ ?

Also, you can try:
```
sudo bash -x ananicy start
sudo bash -x ananicy dump rules
```

**Comment by ryanmusante** [comment]
Latest Git install fixed problem for me.

**Comment by terencode** [comment]
@Nefelim4ag Nope, didn't have an empty configuration directory and 
those commands seem to work as expected.

**Comment by terencode** [comment]
Could this be related? https://www.reddit.com/r/archlinux/comments/8cpmco/headsup_regarding_latest_pgrep_update/?utm_source=reddit-android

**Comment by Nefelim4ag** [comment]
@terencode, possible, but i have latest version of pgrep, ananicy work as expected and pgrep --ns 0 not working.

Anyway, i've rewrite ananicy from scratch on python, you can give it a try.
That's not 1 to 1 port, but most of things work.
You can give it a try.

Thanks.

**Comment by terencode** [comment]
@Nefelim4ag just tried the new version, everything works as expected, closing...

**Comment by terencode** [comment]
@Nefelim4ag it looks like it takes more cpu resources though.

**Comment by Nefelim4ag** [comment]
@terencode,
How you observe that?
Does you try change check_freq in config?

I use systemctl status ananicy to compare cpu time.

For my system, old version use:
~5h of 10h runtime. - 50% of one cpu
New:
~1h of 10h runtime. - 10% of one cpu
With check_freq=5.

I.e. new version didn't have pauses in logic, so `in theory` peac usage, can be up to 100%, but overall system usage must be lower.

Thanks.

**Comment by terencode** [comment]
With htop.
I do not have a CPU entry with systemctl status...

**Comment by Nefelim4ag** [comment]
@terencode, that will not work as expected.
i.e. htop show cpu usage of process.
For Bash Ananicy, bash it self do nothing, for every work it's spawn new process, bash, pgrep, sched & etc.
So main daemon will have low numbers.

For Python Ananicy, most logic work in one process, and only tools for monitor/change nice, ionice & etc will be spawned.

So, as Ananicy python do most work itself, number for main pid will be higher.

As example:
htop show ananicy use 27.09.17 cpu time
At same time, Cgroups metric:
CPU: 43min 46.499s

So 43-27 = 16 min of CPU, that's are other processes spawned by ananicy.

I didn't have such metrics for old ananicy, but main idea must be clean.

Thanks.
