### ISSUE TITLE
Unable to match process with space

### ISSUE THREAD

**Issue by terencode** [Nefelim4ag/Ananicy#93]
I'm not able to match the following process:     
>"6883": {
        "tpid": 6883,
        "exe": "/usr/bin/pianoteq 6",
        "cmd": "pianoteq 6",
        "nice": 0,
        "oom_score_adj": 0,
        "stat": "6883 (Pianoteq STAGE) S 13537 13477 13477 1026 13477 1077936192 35 538 0 0 17086 191 0 0 -66 0 8 0 7261007 864665600 75982 18446744073709551615 4194304 48096598 140734162512208 0 0 0 4096 16777216 16896 0 0 0 -1 0 65 2 0 0 0 50197376 50665096 72962048 140734162520335 140734162520346 140734162520346 140734162522084 0",
        "cmdline": "pianoteq 6"
    }

I tried using ``NAME="pianoteq" TYPE=LowLatency_RT`` as advised in #83 but it's not working.

**Comment by Nefelim4ag** [comment]
Oh, i sure that because rule parser works not good enough, and didn't understood quotes.
You can see at dump rules, if you write:
NAME="pianoteq 6"

In dump you will see only pianoteq

**Comment by Nefelim4ag** [comment]
@terencode,
i think, ananicy must change rules/types format,
because that works good for bash works with problems for python.

I think about json per line, like:
{"name": "pianoteq 6", "nice": -10}

That must works good.

**Comment by Nefelim4ag** [comment]
@terencode,
Check that

**Comment by terencode** [comment]
@Nefelim4ag Nice, everything works :smile:
