### ISSUE TITLE
cgroup permission error

### ISSUE THREAD

**Issue by terencode** [Nefelim4ag/Ananicy#99]
>avril 22 14:21:25 terence-arch ananicy[25480]: OSError: [Errno 30] Read-only file system: '/sys/fs/cgroup/cpu,cpuacct'
avril 22 14:21:25 terence-arch ananicy[25480]:     mkdir(name, mode)
avril 22 14:21:25 terence-arch ananicy[25480]:   File "/usr/lib/python3.6/os.py", line 220, in makedirs
avril 22 14:21:25 terence-arch ananicy[25480]:     makedirs(head, mode, exist_ok)
avril 22 14:21:25 terence-arch ananicy[25480]:   File "/usr/lib/python3.6/os.py", line 210, in makedirs
avril 22 14:21:25 terence-arch ananicy[25480]:     os.makedirs(self.work_path)
avril 22 14:21:25 terence-arch ananicy[25480]:   File "/usr/bin/ananicy", line 41, in __init__
avril 22 14:21:25 terence-arch ananicy[25480]:     self.cgroups[cgroup] = CgroupController(cgroup, cpuquota)
avril 22 14:21:25 terence-arch ananicy[25480]:   File "/usr/bin/ananicy", line 240, in get_cgroup_info
avril 22 14:21:25 terence-arch ananicy[25480]:     self.get_cgroup_info(line)
avril 22 14:21:25 terence-arch ananicy[25480]:   File "/usr/bin/ananicy", line 217, in load_cgroups
avril 22 14:21:25 terence-arch ananicy[25480]:     self.load_cgroups()
avril 22 14:21:25 terence-arch ananicy[25480]:   File "/usr/bin/ananicy", line 117, in __init__
avril 22 14:21:25 terence-arch ananicy[25480]:     daemon = Ananicy()
avril 22 14:21:25 terence-arch ananicy[25480]:   File "/usr/bin/ananicy", line 595, in main
avril 22 14:21:25 terence-arch ananicy[25480]:     main(sys.argv)
avril 22 14:21:25 terence-arch ananicy[25480]:   File "/usr/bin/ananicy", line 613, in <module>
avril 22 14:21:25 terence-arch ananicy[25480]: Traceback (most recent call last):
avril 22 14:21:25 terence-arch ananicy[25480]: Load types: /etc/ananicy.d//00-cgroups.cgroups

**Comment by Nefelim4ag** [comment]
@terencode, that's strange
```
sudo mkdir -p /sys/fs/cgroup/cpu,cpuacct/test ?
```

for now, you can just delete cgroups file.

**Comment by terencode** [comment]
@Nefelim4ag 
>mkdir: cannot create directory ‘/sys/fs/cgroup/cpu,cpuacct’: Read-only file system

**Comment by Nefelim4ag** [comment]
```
➜  Ananicy git:(master) mount | grep cgroup
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
```

**Comment by terencode** [comment]
> tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,nosuid,nodev,noexec,relatime,cpu)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)

**Comment by Nefelim4ag** [comment]
You just don't have cpuacct

Strange.
```
zgrep -i cpuacct /proc/config.gz 
CONFIG_CGROUP_CPUACCT=y
```

Which linux distro you use?

**Comment by terencode** [comment]
I'm using linux-ck kernel from AUR. I guess I need to rebuilt it.

**Comment by terencode** [comment]
@Nefelim4ag now: 
>avril 22 16:27:42 terence-arch ananicy[20662]: File: /etc/ananicy.d//00-cgroups.cgroups, Line: 7, Error: cgroup fs: cpu,cpuacct missing
avril 22 16:27:42 terence-arch ananicy[20662]: File: /etc/ananicy.d//00-cgroups.cgroups, Line: 6, Error: cgroup fs: cpu,cpuacct missing
avril 22 16:27:42 terence-arch ananicy[20662]: Load cgroup: /etc/ananicy.d//00-cgroups.cgroups

**Comment by terencode** [comment]
Is cpuact required for cgroup support?

**Comment by Nefelim4ag** [comment]
Not sure, i'm not very familiar with cgroups internal

But i found that some thing created symlink cpu -> cpu,cpuacct.
So, https://github.com/Nefelim4ag/Ananicy/commit/1b5e90cb6aba07b2178370766379df99596a63a3

**Comment by terencode** [comment]
@Nefelim4ag uhh now I have this:
>avril 22 17:06:27 terence-arch systemd[1]: ananicy.service: Main process exited, code=exited, status=1/FAILURE
avril 22 17:06:27 terence-arch ananicy[9733]: PermissionError: [Errno 13] Permission denied: '/sys/fs/cgroup/cpu/cpu90/cpu.cfs_period_us'
avril 22 17:06:27 terence-arch ananicy[9733]:     open(self.work_path + "/cpu.cfs_period_us", 'w').write(str(self.period_us))
avril 22 17:06:27 terence-arch ananicy[9733]:   File "/usr/bin/ananicy", line 51, in __init__
avril 22 17:06:27 terence-arch ananicy[9733]:     self.cgroups[cgroup] = CgroupController(cgroup, cpuquota)
avril 22 17:06:27 terence-arch ananicy[9733]:   File "/usr/bin/ananicy", line 243, in get_cgroup_info
avril 22 17:06:27 terence-arch ananicy[9733]:     self.get_cgroup_info(line)
avril 22 17:06:27 terence-arch ananicy[9733]:   File "/usr/bin/ananicy", line 220, in load_cgroups
avril 22 17:06:27 terence-arch ananicy[9733]:     self.load_cgroups()
avril 22 17:06:27 terence-arch ananicy[9733]:   File "/usr/bin/ananicy", line 120, in __init__
avril 22 17:06:27 terence-arch ananicy[9733]:     daemon = Ananicy()
avril 22 17:06:27 terence-arch ananicy[9733]:   File "/usr/bin/ananicy", line 598, in main
avril 22 17:06:27 terence-arch ananicy[9733]:     main(sys.argv)
avril 22 17:06:27 terence-arch ananicy[9733]:   File "/usr/bin/ananicy", line 616, in <module>
avril 22 17:06:27 terence-arch ananicy[9733]: Traceback (most recent call last):
avril 22 17:06:27 terence-arch ananicy[9733]: Load cgroup: /etc/ananicy.d//00-cgroups.cgroups

**Comment by Nefelim4ag** [comment]
I think that's files are RO for BFQ/MuQSS, so looks like that will not work.

And that: https://github.com/Nefelim4ag/Ananicy/commit/50cd69c1c60dcec714baaf4f9c678b5b12ebafec

**Comment by terencode** [comment]
OK, now: 
>avril 22 21:45:44 terence-arch ananicy[25340]: File: /etc/ananicy.d//00-cgroups.cgroups, Line: 7, Error: [Errno 13] Permission denied: '/sys/fs/cgroup/cpu/cpu80/cpu.cfs_period_us'
avril 22 21:45:44 terence-arch ananicy[25340]: File: /etc/ananicy.d//00-cgroups.cgroups, Line: 6, Error: [Errno 13] Permission denied: '/sys/fs/cgroup/cpu/cpu90/cpu.cfs_period_us'
avril 22 21:45:44 terence-arch ananicy[25340]: Load cgroup: /etc/ananicy.d//00-cgroups.cgroups

**Comment by Nefelim4ag** [comment]
@terencode,
that's only thing what i can do, if kernel not support cpu cgroup.
Handle errors and let's ananicy works.
